export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_ERROR = "ADD_USER_ERROR";
export const ADD_USER_RESET_STATE = "ADD_USER_RESET_STATE";

export const ADD_COMPANY_REQUEST = "ADD_COMPANY_REQUEST";
export const ADD_COMPANY_SUCCESS = "ADD_COMPANY_SUCCESS";
export const ADD_COMPANY_ERROR = "ADD_COMPANY_ERROR";
export const ADD_COMPANY_RESET_STATE = "ADD_COMPANY_RESET_STATE";

export const ADD_SPARE_REQUEST = "ADD_SPARE_REQUEST";
export const ADD_SPARE_SUCCESS = "ADD_SPARE_SUCCESS";
export const ADD_SPARE_ERROR = "ADD_SPARE_ERROR";
export const ADD_SPARE_RESET_STATE = "ADD_SPARE_RESET_STATE";

export const ADD_ASSET_REQUEST = "ADD_ASSET_REQUEST";
export const ADD_ASSET_SUCCESS = "ADD_ASSET_SUCCESS";
export const ADD_ASSET_ERROR = "ADD_ASSET_ERROR";
export const ADD_ASSET_RESET_STATE = "ADD_ASSET_RESET_STATE";

export const ADD_ASSET_SPARE_REQUEST = "ADD_ASSET_SPARE_REQUEST";
export const ADD_ASSET_SPARE_SUCCESS = "ADD_ASSET_SPARE_SUCCESS";
export const ADD_ASSET_SPARE_ERROR = "ADD_ASSET_SPARE_ERROR";
export const ADD_ASSET_SPARE_RESET_STATE = "ADD_ASSET_SPARE_RESET_STATE";

export const GET_COMPANIES_REQUEST = "GET_COMPANIES_REQUEST";
export const GET_COMPANIES_SUCCESS = "GET_COMPANIES_SUCCESS";
export const UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS";
export const GET_COMPANIES_ERROR = "GET_COMPANIES_ERROR";
export const GET_COMPANIES_RESET_STATE = "GET_COMPANIES_RESET_STATE";

export const GET_CLIENT_USERS_REQUEST = "GET_CLIENT_USERS_REQUEST";
export const GET_CLIENT_USERS_SUCCESS = "GET_CLIENT_USERS_SUCCESS";
export const GET_CLIENT_USERS_ERROR = "GET_CLIENT_USERS_ERROR";

export const GET_SPARES_REQUEST = "GET_SPARES_REQUEST";
export const GET_SPARES_SUCCESS = "GET_SPARES_SUCCESS";
export const GET_SPARE_BY_ID_SUCCESS = "GET_SPARE_BY_ID_SUCCESS";
export const UPDATE_SPARE_SUCCESS = "UPDATE_SPARE_SUCCESS";
export const DELETE_SPARE_SUCCESS = "DELETE_SPARE_SUCCESS";
export const GET_SPARES_ERROR = "GET_SPARES_ERROR";
export const GET_SPARES_RESET_STATE = "GET_SPARES_RESET_STATE";

export const GET_COMPANY_ASSETS_REQUEST = "GET_COMPANY_ASSETS_REQUEST";
export const GET_COMPANY_ASSETS_SUCCESS = "GET_COMPANY_ASSETS_SUCCESS";
export const UPDATE_COMPANY_ASSET_SUCCESS = "UPDATE_COMPANY_ASSET_SUCCESS";
export const DELETE_COMPANY_ASSET_SUCCESS = "DELETE_COMPANY_ASSET_SUCCESS";
export const GET_COMPANY_ASSETS_ERROR = "GET_COMPANY_ASSETS_ERROR";
export const GET_COMPANY_ASSETS_RESET_STATE = "GET_COMPANY_ASSETS_RESET_STATE";

export const GET_ASSET_SPARES_REQUEST = "GET_ASSET_SPARES_REQUEST";
export const GET_ASSET_SPARES_SUCCESS = "GET_ASSET_SPARES_SUCCESS";
export const DELETE_ASSET_SPARE_SUCCESS = "DELETE_ASSET_SPARE_SUCCESS";
export const GET_ASSET_SPARES_ERROR = "GET_ASSET_SPARES_ERROR";

export const GET_COMPANY_ASSET_BY_ID_REQUEST =
  "GET_COMPANY_ASSET_BY_ID_REQUEST";
export const GET_COMPANY_ASSET_BY_ID_SUCCESS =
  "GET_COMPANY_ASSET_BY_ID_SUCCESS";
export const GET_COMPANY_ASSET_BY_ID_ERROR = "GET_COMPANY_ASSET_BY_ID_ERROR";
