export const GET_CART_INFO_REQUEST = "GET_CART_INFO_REQUEST";
export const ADD_CART_ITEM_SUCCESS = "ADD_CART_ITEM_SUCCESS";
export const REMOVE_CART_ITEM_SUCCESS = "REMOVE_CART_ITEM_SUCCESS";
export const CHANGE_CART_ITEM_QUANTITY_SUCCESS =
  "CHANGE_CART_ITEM_QUANTITY_SUCCESS";
export const GET_CART_INFO_ERROR = "GET_CART_INFO_ERROR";
